[toolchain]
anchor_version = "0.30.1"

[features]
resolution = true
skip-lint = false

[programs.localnet]
istolo_escrow = "Fg6PaFpoGXkYsidMpWxTWqkZxYwGz3Y9VdQzN9wW8m3"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "anchor test"
